services:
  db:
    build: ./docker/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sampleapp
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sampleapp
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
