site_name: Sample Boot App Documentation
theme:
  name: material
  language: ja
docs_dir: doc
nav:
  - Home: index.md
  - API List: api-list.md
  - Architecture: architecture.md
  - Context Map: context-map.md
  - Domain Models: domain-models.md
  - Features: features.md
  - Reports:
      - Unit Test Report: /reports/unit-test/index.html
      - Coverage Report: /reports/coverage/index.html
      - Static Analysis Report: /reports/static-analysis/index.html
      - Integration Test Report: /reports/integration-test/index.html
      - Fitness Test Report: /reports/fitness-test/index.html
