spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sampleapp
    username: sampleapp
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration

mybatis:
  configuration:
    map-underscore-to-camel-case: true
