name: Fitness Check

on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: write

jobs:
  fitness-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run Fitness Tests
        run: ./gradlew fitnessTest

      - name: Upload Fitness Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fitness-test-report
          path: build/reports/tests/fitnessTest

      - name: Deploy to GitHub Pages
        if: always() # テスト失敗時もレポートは見たい
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/reports/tests/fitnessTest
          destination_dir: reports/fitness-test
          keep_files: true
